#!/usr/bin/env bash
# set -o errexit -o errtrace -o noclobber -o nounset -o pipefail
# IFS=$'\n\t'

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
project_dir=$(cd "$(dirname "$script_dir")" && pwd)

cd "$project_dir" || exit

template_file_name="$script_dir/github-actions-templates.md"

place_holder="insert:templates:here"
place_holder_line=$(grep --line-number --no-filename "$place_holder" task/github-actions-templates.md | cut -d: -f1)

if [[ -z "$place_holder_line" ]]; then
  (>&2 echo "Cannot find placeholder $place_holder in $template_file_name")
  exit 1
fi

output_file_name="docs/$(basename "$template_file_name")"

mkdir -p "$(dirname "$output_file_name")"

# Empty the output file
: >| "$output_file_name"

cat >> "$output_file_name" <<EOF
<!-- DO NOT EDIT THIS FILE!

It was automatically created by ${BASH_SOURCE[0]} at $(date).
-->
EOF

# Template content before place holder
head --lines="$((place_holder_line-1))" "$template_file_name" >> "$output_file_name"

for f in github/workflows/*.yaml; do
  # Separator
  cat >> "$output_file_name" <<EOF

---

[$f]($f)

EOF

  # Extract actual template documentation block
  grep -E '^###( |$)' "$f" | sed -E -e 's/^### ?//' >> "$output_file_name"
done

# Template content after place holder
tail --lines="+$((place_holder_line+1))" "$template_file_name" >> "$output_file_name"

echo "$output_file_name"
