
version: '3'

networks:
  frontend:
    external: true

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - frontend
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD/traefik.yml:/traefik.yml:ro
      - $PWD/dynamic-conf.yaml:/config/dynamic-conf.yaml:ro
      - $PWD/ssl:/certs:ro
    labels:
      - "traefik.enable=true"
      - "traefik.log.level=DEBUG"
      - "traefik.http.routers.traefik.rule=Host(`traefik.local.itkdev.dk`)"
