---
networks:
  frontend:
    external: true
  proxy:
    driver: bridge
    internal: true

services:
  socket-proxy:
    image: itkdev/docker-socket-proxy
    user: root
    container_name: socket-proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: 1
    networks:
      - proxy

  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - frontend
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - $PWD/traefik.yml:/traefik.yml:ro
      - $PWD/dynamic-conf.yaml:/config/dynamic-conf.yaml:ro
      - $PWD/ssl:/certs:ro
    labels:
      - "traefik.enable=true"
      - "traefik.log.level=DEBUG"
      - "traefik.http.routers.traefik.rule=Host(`traefik.local.itkdev.dk`)"
