on:
  pull_request:
    paths:
      - "github/**"
      - ".github/**"
      - "config/**"
      - "task/scripts/**"
      - "docs/**"

name: Github Actions documentation

env:
  COMPOSE_USER: runner

jobs:
  check-github-actions-documentation:
    runs-on: ubuntu-latest
    name: Check that Github Actions documentation is up to date
    steps:
      - uses: actions/checkout@v7
      - uses: go-task/setup-task@v2

      # https://github.com/mxschmitt/action-tmate?tab=readme-ov-file#manually-triggered-debug
      # Enable tmate debugging if debug logging is enabled (cf.
      # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#runner-context)
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: 1 == runner.debug

      - run: |
          task github-actions:documentation:update

      # Check that documentation has not changed.
      - run: |
          task github-actions:documentation:diff

  check-github-actions-template-headers:
    runs-on: ubuntu-latest
    name: Check that Github Actions template headers are up to date
    steps:
      - uses: actions/checkout@v7
      - uses: go-task/setup-task@v2
      - run: |
          task github-actions:template-headers:update --yes
      # Check that files have not changed.
      - run: |
          git diff --exit-code

  check-config-file-headers:
    runs-on: ubuntu-latest
    name: Check that config file headers are up to date
    steps:
      - uses: actions/checkout@v7
      - uses: go-task/setup-task@v2
      - run: |
          task github-actions:config-headers:update --yes
      # Check that files have not changed.
      - run: |
          git diff --exit-code

  check-links:
    runs-on: ubuntu-latest
    name: Check that workflow and config file links are up to date
    steps:
      - uses: actions/checkout@v7
      - uses: go-task/setup-task@v2
      - run: |
          task github-actions:link --yes
      # Check that files have not changed.
      - run: |
          git diff --exit-code
