on: pull_request
name: Review
jobs:
  validate-compose:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ 'drupal-7', 'drupal-8', 'drupal-10', 'drupal-7', 'symfony-3', 'symfony-4', 'symfony-6' ]
    name: Validate compose (${{ matrix.version }})
    steps:
      - uses: actions/checkout@master

      - name: Validate local docker compose files
        run: |
          DC=$(COMPOSE_DOMAIN=test.itkdev.dk docker compose --file templates/${{ matrix.version }}/docker-compose.yml config --quiet 2>&1)
          [ -z "$DC" ] || { echo $DC; exit 1; }

      - name: Validate server docker compose files
        run: |
          DC=$(COMPOSE_SERVER_DOMAIN=test.itkdev.dk docker compose --file templates/${{ matrix.version }}/docker-compose.server.yml config --quiet 2>&1)
          [ -z "$DC" ] || { echo $DC; exit 1; }
          DC=$(COMPOSE_SERVER_DOMAIN=test.itkdev.dk docker compose --file templates/${{ matrix.version }}/docker-compose.server.yml --file templates/${{ matrix.version }}/docker-compose.dev.yml config --quiet 2>&1)
          [ -z "$DC" ] || { echo $DC; exit 1; }
          DC=$(COMPOSE_SERVER_DOMAIN=test.itkdev.dk docker compose --file templates/${{ matrix.version }}/docker-compose.server.yml --file templates/${{ matrix.version }}/docker-compose.redirect.yml config --quiet 2>&1)
          [ -z "$DC" ] || { echo $DC; exit 1; }
