on: pull_request
name: Review
jobs:
  validate-compose:
    runs-on: ubuntu-latest
    env: &env
      # All environment variables that require a non-empty value in our compose
      # files (cf.
      # https://docs.docker.com/reference/compose-file/interpolation/)
      COMPOSE_DOMAIN: test.local.example.org
      COMPOSE_PROJECT_NAME: test_project
      COMPOSE_SERVER_DOMAIN: test.example.org
    strategy:
      fail-fast: false
      matrix:
        version: &template_version
          - drupal-7
          - drupal-8
          - drupal-9
          - drupal-10
          - drupal-11
          - symfony-3
          - symfony-4
          - symfony-6
    name: Validate compose (${{ matrix.version }})
    steps:
      - uses: actions/checkout@v5

      - name: Validate local docker compose files
        run: |
          DC=$(docker compose --file templates/${{ matrix.version }}/docker-compose.yml config --quiet 2>&1)
          [ -z "$DC" ] || { echo $DC; exit 1; }

      - name: Validate server docker compose files
        run: |
          DC=$(docker compose --file templates/${{ matrix.version }}/docker-compose.server.yml config --quiet 2>&1)
          [ -z "$DC" ] || { echo $DC; exit 1; }
          DC=$(docker compose --file templates/${{ matrix.version }}/docker-compose.server.yml --file templates/${{ matrix.version }}/docker-compose.dev.yml config --quiet 2>&1)
          [ -z "$DC" ] || { echo $DC; exit 1; }
          DC=$(docker compose --file templates/${{ matrix.version }}/docker-compose.server.yml --file templates/${{ matrix.version }}/docker-compose.redirect.yml config --quiet 2>&1)
          [ -z "$DC" ] || { echo $DC; exit 1; }

  validate-nginx-conf:
    runs-on: ubuntu-latest
    env: *env
    strategy:
      fail-fast: false
      matrix:
        version: *template_version
        compose_file:
          - docker-compose.yml
          - docker-compose.server.yml

    name: Validate nginx conf (${{ matrix.version }}/${{ matrix.compose_file}})
    steps:
      - uses: actions/checkout@v5

      - name: Create docker network
        run: |
          docker network create frontend

      - name: Validate nginx conf
        run: |
          docker compose --file templates/${{ matrix.version }}/${{ matrix.compose_file}} run --rm nginx nginx -t
