on: pull_request

name: Workflow templates

jobs:
  check-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - run: |
          docker pull mikefarah/yq
          for f in $(find github/workflows/ -name '*.yaml'); do
            docker run --rm --volume "$PWD":/workdir mikefarah/yq "$f" > /dev/null
          done

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: go-task/setup-task@v1

      - run: |
          task lint:shell-script
