on: pull_request

name: Workflow templates

jobs:
  # https://github.com/rhysd/actionlint/blob/v1.7.10/docs/usage.md#use-actionlint-on-github-actions
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Check workflow files
        # uses: docker://rhysd/actionlint:latest
        # with:
        #   args: -color github/workflows/*.yaml github/workflows/*/*.yaml
        # @todo Can we make globbing work in `with.args`?
        run: |
          docker run --rm --volume "$PWD":/repo --workdir /repo rhysd/actionlint:latest -color github/workflows/*.yaml github/workflows/*/*.yaml

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: go-task/setup-task@v1

      - run: |
          task lint:shell-script
